format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$git_branch$golang$rust$python$package
[└─>](bold green) """

[directory]
truncation_length = 8

[git_branch]
symbol = "🌲 "
truncation_length = 4
truncation_symbol = ""

[golang]
format = "Go [$symbol $version]($style) "

[kubernetes]
prefix = "(k8s)"
disabled = true
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[python]
pyenv_version_name = true
python_binary = ["python"]
disabled = true
