
format="""\
    $directory\
    $golang\
    $rust\
    $kubernetes\
    $package\
    $python\
    """

[directory]
truncation_length = 8

[git_branch]
symbol = "🌲 "
truncation_length = 4
truncation_symbol = ""

[golang]
prefix = "(go)"

[rust]
prefix = "(rust)"

[kubernetes]
prefix = "(k8s)"
disabled = true
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

